# Generated by Django 4.2 on 2026-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(default='Unknown', max_length=300)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('num_reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('book_url', models.URLField(max_length=1000)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_genre', models.CharField(blank=True, max_length=200)),
                ('ai_sentiment', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
